ARG GO_IMAGE
FROM ${GO_IMAGE} AS builder

RUN --mount=type=bind,target=/go/src,source=. \
    version=$(git describe --tags || git rev-parse HEAD) && \
    go_module=$(grep "module" go.mod | head -1 | cut -d ' ' -f 2) && \
    go get -C cli && \
    go build -C cli \
        -ldflags "-s -w -X '${go_module}/shared.Version=${version}'" \
        -o /go/bin/steamcmd-cli


FROM scratch
COPY --from=builder /go/bin/steamcmd-cli /bin/steamcmd-cli

ENTRYPOINT [ "/bin/steamcmd-cli", "server" ]
